### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yurayu1985** [Widiskel/cowtopia-bot#2]
Error

> cowtopia-mining-bot@1.0.0 start
> mkdir -p app/config && cp -r config/config.js app/config/config.js && node app/index.js

**Comment by Widiskel** [comment]
thats not error, please provide error message

**Comment by copycatcodex** [comment]
If you have done steps such as creating a session, and changing the HASH & ID API in config, then try this command >**node app/index.js**
